[package]
name = "pgsqltest"
version = "0.1.0"
authors = ["Valentí Jové <valenti@onna.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["macros"] }
tokio-postgres = "*"